version: '3.8'
services:
  db:
    deploy:
      replicas: 3
      restart_policy:
        condition: none
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=media_center
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432-5435:5432'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - studying

  admin_dashboard:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - studying

volumes:
  db:
    driver: local

networks:
  studying:
    driver: bridge
