version: '3.8'
services:
  db:
    env_file:
      - .env
    deploy:
      replicas: 3
      restart_policy:
        condition: none
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - studying

  admin_dashboard:
    env_file:
      - .env
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORTS}
    depends_on:
      - db
    networks:
      - studying

volumes:
  db:
    driver: local

networks:
  studying:
    driver: bridge
