version: '3.8'
services:
  db:
    container_name: "studying-postgres"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/volume/lib/postgresql/data
volumes:
  db:
    driver: local
