version: '3.8'
services:
  db:
    container_name: "studying-postgres"
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=media_center
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
